version: "3"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - 50070:50070
    networks:
      - hive-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks:
      - hive-net

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    networks:
      - hive-net

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - SERVICE_NAME=metastore
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - hive-metastore-postgresql
    networks:
      - hive-net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - SERVICE_NAME=hiveserver2
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - 10000:10000
    depends_on:
      - hive-metastore
    networks:
      - hive-net

networks:
  hive-net:
    driver: bridge
